spring.application.name=bookstore
server.port=9086
spring.datasource.url=jdbc:mysql://localhost:3306/book.db
spring.datasource.username=root
spring.datasource.password=687433zz

spring.jpa.hibernate.ddl-auto=update