spring.application.name=Book
server.port = 4499
spring.datasource.url=jdbc:mysql://localhost:3306/book_project_db
spring.datasource.username=root
spring.datasource.password=687433zz
spring.jpa.hibernate.ddl-auto=update
